apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "your-root-password"  # Set a strong password
            - name: MYSQL_DATABASE
              value: "mydatabase"  # Optional: Set a default database
          ports:
            - containerPort: 3306
