# permissions for end users to view migrations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: migration-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: practice
    app.kubernetes.io/part-of: practice
    app.kubernetes.io/managed-by: kustomize
  name: migration-viewer-role
rules:
- apiGroups:
  - api.my.domain
  resources:
  - migrations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.my.domain
  resources:
  - migrations/status
  verbs:
  - get
