# create a daemonset for buildah
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: buildah
  namespace: docker-registry
  labels:
    app: buildah
spec:
  selector:
    matchLabels:
      app: buildah
  template:
    metadata:
      labels:
        app: buildah
    spec:
      containers:
      - name: buildah
        image: quay.io/buildah/stable:latest
        securityContext:
          privileged: true
        volumeMounts:
        - name: checkpointed-image
          mountPath: /var/lib/kubelet/checkpoints/
        command:
        - /bin/sh
        - -c
        - while true; do sleep 3600; done
      volumes:
      - name: checkpointed-image
        hostPath:
          path: /var/lib/kubelet/checkpoints/