apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: docker-registry
  labels:
    app: docker-registry
  namespace: docker-registry
spec:
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      containers:
      - name: docker-registry
        image: registry:latest
        ports:
        - containerPort: 5000
          name: registry
        volumeMounts:
        - name: my-persistent-volume
          mountPath: /var/lib/registry
        # set the username and password
        env:
        - name: REGISTRY_AUTH
          value: htpasswd
        - name: REGISTRY_AUTH_HTPASSWD_REALM
          value: Registry Realm
        - name: REGISTRY_AUTH_HTPASSWD_PATH
          value: /auth/htpasswd

      volumes:
      - name: my-persistent-volume
        persistentVolumeClaim:
          claimName: nfs-test
      - name: my-auth-volume
        secret:
          secretName: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry-service
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 31000
    targetPort: 5000
    nodePort: 31000 # Specify the NodePort here
  selector:
    app: docker-registry
