apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: docker-registry
  labels:
    app: docker-registry
  namespace: docker-registry
spec:
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      containers:
      - name: docker-registry
        image: registry:latest
        ports:
        - containerPort: 5000
          name: registry
        volumeMounts:
        - name: my-persistent-volume
          mountPath: /var/lib/registry
        env:
        - name: REGISTRY_HTTP_SECRET
          # mypasswd
          value: myuser:$2y$05$SC5AAIwwjc54t4h4XQEFXey5a5xEkdH6sR7SiwzSTRqvVpa6R2HbW

      volumes:
      - name: my-persistent-volume
        persistentVolumeClaim:
          claimName: nfs-test
        # Assuming /auth is the directory containing the htpasswd file

---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry-service
  namespace: docker-registry
spec:
  # type: ClusterIP
  # ports:
  # - protocol: TCP
  #   port: 30010
  #   targetPort: 5000
  #   # nodePort: 30010 # Specify the NodePort here
  # selector:
  #   app: docker-registry
  type: NodePort
  ports:
  - protocol: TCP
    port: 30010
    targetPort: 5000
    nodePort: 30010 # Specify the NodePort here
  selector:
    app: docker-registry
