apiVersion: v1
kind: Pod
metadata:
  name: stress-test
  labels:
    app: stress
  namespace: default
spec:
  containers:
  - name: stress
    image: polinux/stress
    command: ["stress"]
    args: ["--cpu", "1", "--io", "1", "--vm", "4", "--vm-bytes", "128M", "--verbose"]
  restartPolicy: Never
  nodeName: workernode01
