# apiVersion: admissionregistration.k8s.io/v1
# kind: ValidatingWebhookConfiguration
# metadata:
#   name: example-webhook
# webhooks:
#   - name: example-webhook.default.svc.cluster.local
#     admissionReviewVersions:
#       - "v1"
#     sideEffects: "None"
#     timeoutSeconds: 30
#     objectSelector:
#       matchLabels:
#         example-webhook-enabled: "true"
#     clientConfig:
#       service:
#         name: example-webhook
#         namespace: default
#         path: "/validate"
#       caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURkRENDQWx5Z0F3SUJBZ0lVU3krcHE3V2o0TG5TcGtDOVhtajFBT0xGcXlNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1VqRUxNQWtHQTFVRUJoTUNRVlV4RURBT0JnTlZCQWdUQjBWNFlXMXdiR1V4RWpBUUJnTlZCQWNUQ1UxbApiR0p2ZFhKdVpURVFNQTRHQTFVRUNoTUhSWGhoYlhCc1pURUxNQWtHQTFVRUN4TUNRMEV3SGhjTk1qUXdPREV6Ck1USXlOREF3V2hjTk1qa3dPREV5TVRJeU5EQXdXakJTTVFzd0NRWURWUVFHRXdKQlZURVFNQTRHQTFVRUNCTUgKUlhoaGJYQnNaVEVTTUJBR0ExVUVCeE1KVFdWc1ltOTFjbTVsTVJBd0RnWURWUVFLRXdkRmVHRnRjR3hsTVFzdwpDUVlEVlFRTEV3SkRRVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFMSEkweHE0CnBEYTVTSVRDbml1VFJqd1E1d2o4ZGFRNnY2TkRQYzhBQ094RWZJQUdEdkRMT21ZV0NOdHY1RlhKeFk0RlF3Q3cKQ3RlSCtuYkpkMlpOMElVTlVQRjEvL0N2RUxHVExkYTZCUVVHL2FxWjNOUU03Z0RCQnovWW1YTDgzc29nSTdjNwptUEcvUFV0QjhkalU4MzVydi9laEN3bkNsRU9ZTkYzbk9XN0g5cm5xOW5sVkk5L09LUTRpZlV2YlVNcm9CYk1RCllVYk9aVTc4ZlhxT09WbXUrMDNjKy9OOVRjcTBNa2xiemlKRktmOTBOc3NMOUg0clNNOStaZEJNVmxUc2VhUzAKVVdYa0pNeDFFMUsvUzhsdS9IWXdrQkh3NW5TbzBYZFJmNGdHbFJhaWwrbjJsL2ZBR3l5NU5uc1RHNkpKQ2t4NAp5VnhXYlk3SHlhRTNxUnNDQXdFQUFhTkNNRUF3RGdZRFZSMFBBUUgvQkFRREFnRUdNQThHQTFVZEV3RUIvd1FGCk1BTUJBZjh3SFFZRFZSME9CQllFRkpVOFZxV1FzQVJHbU5tTlluTGpJY3NVeDM0ME1BMEdDU3FHU0liM0RRRUIKQ3dVQUE0SUJBUUJYWjhPMUJpQU9SY3hwRm1KSS9SU2RwY1lUdnhDZHhJbDJXaFZxZzloSmtGMFJBNForcHZGdApoRnF4ODgwejJuOGd4U0w4a013Vlh6RUlNTlBuSS9Vd0Zqa3lHMzhHL1RsS1JQaWg0bjFrbUxNSmZ0SncwcDRkCjdVRGRscXh6RXlqSllVR1ZsclMxbGdxYTM2SUlaU2pDVGwwcURFcG9MV3FHaDdMODhZVmY3UTBFeXV5ekhNOE8KdGlqNGpiL1VjL3hHSVd3bmlMTGdpVmxUZXhPWDY5ODA5a0JOVVpPRkZqc0JoMEhVZVpiV29Zdm5sYzNBK1lVQgozOGViR0dtcnZVRFV5cktjbVBZd3ZsaEhFSWhhRERBQmNmR2RNemMxK3dCcUVKK0dlV05sWGM5TTZEOFFndlpICnYvb3lqTG03cmN3QU1FZkJIVk9LRmNyVWlURk5rUUxyCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
#     rules:
#     - apiGroups:   ["api.my.domain"]        # Target the correct API group
#       apiVersions: ["v1alpha1"]             # Target the correct version
#       operations:  ["CREATE", "UPDATE"]     # Validate both creation and updates
#       resources:   ["migrations"]           # Target the 'migrations' resource
#       scope:       "Namespaced"
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: example-webhook
webhooks:
  - name: example-webhook.default.svc.cluster.local
    admissionReviewVersions:
      - "v1beta1"
    sideEffects: "None"
    timeoutSeconds: 30
    objectSelector:
      matchLabels:
        example-webhook-enabled: "true"
    clientConfig:
      service:
        name: example-webhook
        namespace: default
        path: "/mutate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURkRENDQWx5Z0F3SUJBZ0lVU3krcHE3V2o0TG5TcGtDOVhtajFBT0xGcXlNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1VqRUxNQWtHQTFVRUJoTUNRVlV4RURBT0JnTlZCQWdUQjBWNFlXMXdiR1V4RWpBUUJnTlZCQWNUQ1UxbApiR0p2ZFhKdVpURVFNQTRHQTFVRUNoTUhSWGhoYlhCc1pURUxNQWtHQTFVRUN4TUNRMEV3SGhjTk1qUXdPREV6Ck1USXlOREF3V2hjTk1qa3dPREV5TVRJeU5EQXdXakJTTVFzd0NRWURWUVFHRXdKQlZURVFNQTRHQTFVRUNCTUgKUlhoaGJYQnNaVEVTTUJBR0ExVUVCeE1KVFdWc1ltOTFjbTVsTVJBd0RnWURWUVFLRXdkRmVHRnRjR3hsTVFzdwpDUVlEVlFRTEV3SkRRVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFMSEkweHE0CnBEYTVTSVRDbml1VFJqd1E1d2o4ZGFRNnY2TkRQYzhBQ094RWZJQUdEdkRMT21ZV0NOdHY1RlhKeFk0RlF3Q3cKQ3RlSCtuYkpkMlpOMElVTlVQRjEvL0N2RUxHVExkYTZCUVVHL2FxWjNOUU03Z0RCQnovWW1YTDgzc29nSTdjNwptUEcvUFV0QjhkalU4MzVydi9laEN3bkNsRU9ZTkYzbk9XN0g5cm5xOW5sVkk5L09LUTRpZlV2YlVNcm9CYk1RCllVYk9aVTc4ZlhxT09WbXUrMDNjKy9OOVRjcTBNa2xiemlKRktmOTBOc3NMOUg0clNNOStaZEJNVmxUc2VhUzAKVVdYa0pNeDFFMUsvUzhsdS9IWXdrQkh3NW5TbzBYZFJmNGdHbFJhaWwrbjJsL2ZBR3l5NU5uc1RHNkpKQ2t4NAp5VnhXYlk3SHlhRTNxUnNDQXdFQUFhTkNNRUF3RGdZRFZSMFBBUUgvQkFRREFnRUdNQThHQTFVZEV3RUIvd1FGCk1BTUJBZjh3SFFZRFZSME9CQllFRkpVOFZxV1FzQVJHbU5tTlluTGpJY3NVeDM0ME1BMEdDU3FHU0liM0RRRUIKQ3dVQUE0SUJBUUJYWjhPMUJpQU9SY3hwRm1KSS9SU2RwY1lUdnhDZHhJbDJXaFZxZzloSmtGMFJBNForcHZGdApoRnF4ODgwejJuOGd4U0w4a013Vlh6RUlNTlBuSS9Vd0Zqa3lHMzhHL1RsS1JQaWg0bjFrbUxNSmZ0SncwcDRkCjdVRGRscXh6RXlqSllVR1ZsclMxbGdxYTM2SUlaU2pDVGwwcURFcG9MV3FHaDdMODhZVmY3UTBFeXV5ekhNOE8KdGlqNGpiL1VjL3hHSVd3bmlMTGdpVmxUZXhPWDY5ODA5a0JOVVpPRkZqc0JoMEhVZVpiV29Zdm5sYzNBK1lVQgozOGViR0dtcnZVRFV5cktjbVBZd3ZsaEhFSWhhRERBQmNmR2RNemMxK3dCcUVKK0dlV05sWGM5TTZEOFFndlpICnYvb3lqTG03cmN3QU1FZkJIVk9LRmNyVWlURk5rUUxyCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]