apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: docker-registry
  name: pod-list-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-list-rolebinding
  namespace: docker-registry
subjects:
- kind: ServiceAccount
  name: default
  namespace: docker-registry
roleRef:
  kind: Role
  name: pod-list-role
  apiGroup: rbac.authorization.k8s.io
