apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhooktest
  labels:
    app: webhooktest
  namespace: docker-registry
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webhooktest
  template:
    metadata:
      labels:
        app: webhooktest
    spec:
      containers:
      - name: webhooktest
        image: tonyliu666/testwebhook:latest
        ports:
        - containerPort: 8080
  
--- 
# deploy pod as a service 

apiVersion: v1
kind: Service
metadata:
  name: webhooktest
  labels:
    app: webhooktest
  namespace: docker-registry
spec:
  selector:
    app: webhooktest
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080