apiVersion: v1
kind: Pod 
metadata:
  name: webhooktest
  labels:
    app: webhooktest
  namespace: docker-registry
spec:
  containers:
  - name: webhooktest
    image: tonyliu666/testwebhook:latest
    ports:
    - containerPort: 8080
  imagePullSecrets:
    - name: regcred
  
--- 
# deploy pod as a service 

apiVersion: v1
kind: Service
metadata:
  name: webhooktest
  labels:
    app: webhooktest
spec:
  selector:
    app: webhooktest
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080