apiVersion: api.my.domain/v1alpha1
kind: Migration
metadata:
  labels:
    app.kubernetes.io/name: migration
    app.kubernetes.io/instance: migration-sample
    app.kubernetes.io/part-of: practice
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: practice
  name: migration-sample
spec:
  # TODO(user): Add fields here
