apiVersion: api.my.domain/v1alpha1
kind: Migration
metadata:
  name: migration-sample
spec:
  # TODO(user): Add fields here
  podname: counter
  deployment: counter-app
  namespace: default
  destination: kubenode03

  # Optional field: deployment
  # Users can choose to include it or leave it empty
  # deployment: 

  
