apiVersion: api.my.domain/v1alpha1
kind: Migration
metadata:
  name: migration-sample
spec:
  # TODO(user): Add fields here
  namespace: default
  podname: counter-app
  # should add destination node
  # destination: kubenode01

  
