apiVersion: api.my.domain/v1alpha1
kind: Migration
metadata:
  name: migration-sample
  namespace: practice-system
spec:
  # TODO(user): Add fields here
  podname: mongodb
  deployment: 
  namespace: default
  destination: workernode01

  # Optional field: deployment
  # Users can choose to include it or leave it empty
  # deployment: 

  
