apiVersion: batch/v1
kind: Job
metadata:
  name: buildah-job-1
  namespace: docker-registry
spec:
  ttlSecondsAfterFinished: 20
  template:
    metadata:
      labels:
        app: buildah
    spec:
      containers:
      - name: buildah
        image: quay.io/buildah/stable
        securityContext:
          privileged: true
          runAsUser: 0
          runAsGroup: 0
        command: ["/bin/bash"]
        args: ["-c", "sleep infinity"]
        volumeMounts:
        - name: checkpointed-image
          mountPath: /var/lib/kubelet/checkpoints/
        workingDir: /
      volumes:
      - name: checkpointed-image
        hostPath:
          path: /var/lib/kubelet/checkpoints/
          type: Directory
      nodeName: workernode01
      restartPolicy: Never
