apiVersion: v1 
kind: Pod
metadata: 
  name: redis
  namespace: default
spec:
  containers:
  - name: redis
    image: redis:latest
  imagePullSecrets:
    - name: regcred
  nodeName: ip-15-0-12-104

  

