apiVersion: v1 
kind: Pod
metadata: 
  name: redis6
  namespace: default
spec:
  containers:
  - name: redis6
    image: redis:latest
  imagePullSecrets:
    - name: regcred
  nodeName: ip-172-31-23-29  

  

