apiVersion: v1
kind: Pod
metadata:
  name: machine-learning
  namespace: ollama
spec:
  containers:
  - name: transformers
    image: tonyliu666/transformer:latest
    resources:
      requests:
        cpu: "2"
      limits:
        cpu: "4"
  nodeName: workernode01


  
  