apiVersion: v1
kind: Pod
metadata:
  name: machine-learning
  namespace: default
spec:
  containers:
  - name: transformers
    image: tonyliu666/transformer:latest
  imagePullSecrets:
    - name: regcred
  nodeName: ip-172-31-23-29