apiVersion: v1
kind: Pod
metadata:
  name: machine-learning
  namespace: ollama
spec:
  containers:
  - name: transformers
    image: tonyliu666/transformer:latest
    
  nodeName: workernode01


  
  