apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-registry-2
  labels:
    storage.k8s.io/name: nfs
    storage.k8s.io/part-of: kubernetes-complete-reference
    storage.k8s.io/created-by: ssbostan
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage-2
  resources:
    requests:
      storage: 50Gi