apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    app.kubernetes.io/name: alpine
    app.kubernetes.io/part-of: kubernetes-complete-reference
    app.kubernetes.io/created-by: ssbostan
spec:
  containers:
    - name: alpine
      image: alpine:latest
      command:
        - touch
        - /mnt/master/file1
      volumeMounts:
        - name: nfs-volume
          mountPath: /mnt/master
  imagePullSecrets:
    - name: regcred
  volumes:
    - name: nfs-volume
      nfs:
        server: 192.168.50.0
        path: /mnt/master
        readOnly: no