apiVersion: v1
kind: Pod 
metadata:
  name: {{ .Values.webhooktest.name }}
  labels:
    app: {{ .Values.webhooktest.name }}
  namespace: {{ .Values.webhooktest.namespace }}
spec:
  containers:
  - name: {{ .Values.webhooktest.name }}
    image: {{ .Values.webhooktest.image.repository }}:{{ .Values.webhooktest.image.tag }}
    ports:
    - containerPort: {{ .Values.webhooktest.ports.targetPort }}
  imagePullSecrets:
    - name: {{ .Values.registry.secret.name }}
  
--- 
# deploy pod as a service 

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webhooktest.name }}
  labels:
    app: {{ .Values.webhooktest.name }}
  namespace: {{ .Values.webhooktest.namespace }}
spec:
  selector:
    app: {{ .Values.webhooktest.name }}
  ports:
  - protocol: {{ .Values.webhooktest.ports.protocol }}
    port: {{ .Values.webhooktest.ports.port }}
    targetPort: {{ .Values.webhooktest.ports.targetPort }}