apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: counter-app
  template:
    metadata:
      labels:
        app: counter-app
    spec:
      containers:
        - name: counter
          image: quay.io/adrianreber/counter:blog
          ports:
            - containerPort: 80