apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  namespace: kafka
spec:
  kafka:
    version: 3.7.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: nodeport
        tls: false  # Set to true if you want TLS
        configuration:
          bootstrap:
            nodePort: 32195
          brokers:
          - broker: 0
            nodePort: 32000
          - broker: 1
            nodePort: 32001
          - broker: 2
            nodePort: 32002
        # authentication:
        #   type: tls
        # configuration:
        #   brokerCertChainAndKey:
        #     certificate: tls.crt
        #     key: tls.key
        #     secretName: kafka-certs
        #   bootstrap:
        #     host: bootstrap.my-kafka.example.com  # Specify the bootstrap host
        #     # brokerCertChainAndKey:
        #     #   certificate: my-cluster-bootstrap-tls
        #   brokers:
        #   - broker: 0
        #     host: broker-0.my-kafka.example.com  # Specify the broker hosts
        #   - broker: 1
        #     host: broker-1.my-kafka.example.com
        #   - broker: 2
        #     host: broker-2.my-kafka.example.com
        #   class: nginx
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.7"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}