name: Build and push operator image to GHCR

on:
  push:
    branches: [ "main", "master" ]
    tags:
      - "v*"
      - "release-*"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  # Use a lowercase image repo name to satisfy container registry naming rules.
  # You can change this to whatever image name you prefer.
  IMAGE_REPO_NAME: checkpoint-operator

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Compute image name (lowercase owner)
        id: vars
        shell: bash
        run: |
          OWNER_LC="$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')"
          echo "OWNER_LC=${OWNER_LC}" >> "$GITHUB_ENV"
          echo "IMAGE=${{ env.REGISTRY }}/${OWNER_LC}/${{ env.IMAGE_REPO_NAME }}" >> "$GITHUB_ENV"
          echo "image=${{ env.REGISTRY }}/${OWNER_LC}/${{ env.IMAGE_REPO_NAME }}" >> "$GITHUB_OUTPUT"

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU (for optional multi-arch builds)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Docker metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE }}
          # Generate useful tags:
          # - branch names (e.g., :main)
          # - git tags (e.g., :v1.2.3)
          # - commit SHA (e.g., :sha-xxxxxxxx)
          # - latest on default branch
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          # Adjust platforms as needed; linux/amd64 is the safest default
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
